Ztisnes/0.1.0
jeremie-gauthier/HyperTube pull request #14
Opened 2021-01-17 08:24 UTC by 0auBSQ

Retriving database setup files before working IITQ-15

2021-01-17 18:01 UTC, jeremie-gauthier requested changes
We should remove express from this project to get the best from NextJS build time optimizations.
Here is an useful link for implementing some auth strategies with Next in a serverless style: 
https://next-auth.js.org/getting-started/introduction

2021-01-18 03:28 UTC, 0auBSQ reviewed
Removed a deprecated file that was only placeholder (using express)

2021-01-19 11:40 UTC, jeremie-gauthier requested changes

2021-01-19 11:40 UTC, jeremie-gauthier commented on package.json
> +    "dev": "npm i next && next dev",
revert this change pls, install and run are 2 differents process.
this command will slow down the start up time

To remove express, run `npm remove express`

2021-01-19 12:48 UTC, jeremie-gauthier commented
@all-contributors please add @0auBSQ for code
@all-contributors please add @zedin27 for code

2021-01-19 12:49 UTC, jeremie-gauthier commented
@all-contributors please add @0auBSQ for code

2021-01-19 12:49 UTC, jeremie-gauthier commented
@all-contributors please add @zedin27  for code

2021-01-19 12:50 UTC, jeremie-gauthier approved these changes

2021-01-19 12:51 UTC, merged